### ISSUE TITLE
ValueError: could not convert string to float: '3\xa0256'

### ISSUE THREAD

**Issue by lupinlicious** [Rurik/Noriben#44]
Hello,

I'm having issues when I try to run noriben.py and I get the following results:

`[*] Termination of Procmon commencing... please wait
[*] Procmon terminated
Traceback (most recent call last):
  File "C:\Analyze\Noriben-master\Noriben.py", line 1060, in parse_csv
    if int(float(reg_length)):
ValueError: could not convert string to float: '3\xa0256'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Analyze\Noriben-master\Noriben.py", line 1512, in <module>
    main()
  File "C:\Analyze\Noriben-master\Noriben.py", line 1499, in main
    parse_csv(csv_file, report, timeline)
  File "C:\Analyze\Noriben-master\Noriben.py", line 1077, in parse_csv
    error_output.append(original_line.strip())
AttributeError: 'list' object has no attribute 'strip'`

I'm running Python version 3.9.1

Even If I try with the followng:

Noriben.py --debug -t 30 
Will results with the same error as above.

How can I resolve this?

First time it worked perfectly, but now it seems to struggle.

Best regards

**Comment by ChristianDasNeves** [comment]
I solved this by adding 
`reg_length = reg_length.replace('’','')` 
on line 1059 of the Noriben.py

**Comment by Rurik** [comment]
This is related to #29 and it'd be helpful if you could provide the respective lines from the "Noriben_*.csv" file. This has come up various times but I don't know why what Procmon is producing that data, nor how to work around it, as I haven't seen the data. I'd need to see the actual line of raw data that's causing this error.

**Comment by ChristianDasNeves** [comment]
Hello here is a link to download the archive with all the logs csv and pml, the version of the procmon and noriben and a screenshot of the error message

https://fb.compass-security.com/d/3LypHwZqD1Jqs6b5AFKcD3PcDyi1CfdgNkuhqAGe

Btw Thank you very much for your work on this project.

Best regards
Christian

**Comment by ChristianDasNeves** [comment]
I've sent you an email with all the files,

Thank you very much for this project, it is very appreciated.

**Comment by ChristianDasNeves** [comment]
> Thanks ChristianDasNevas for your reply.
> 
> On line 1059, I only have **try:**
> 
> If I remove try: with reg_length = reg_length.replace('’','')
> Results: if int (float(reg_length)); IndentationError: unexpected indent.
> 
> If I have: reg_length = reg_length.replace('’','') **try:**
> Results: SyntaxError: invalid syntax
> 
> Or
> 
> **try:** reg_length = reg_length.replace('’','')
> Results: IndentationError: Unexpected indent
> 
> I'm running Noriben 1.8.4
> Which version did you patch?
> 
> Any suggestions?

Like this:
![fix](https://user-images.githubusercontent.com/6506983/114697749-9176e500-9d1e-11eb-98c4-3c99fc9c026b.png)

``

**Comment by lupinlicious** [comment]
Thank you ChristianDasNeves and Brian for your effort in this project.

Everything seems to be working again :)

**Comment by Rurik** [comment]
Thank you for bringing this up, and thank you @ChristianDasNeves!

I've pushed a new minor version up and have implemented that change into it.

**Comment by lupinlicious** [comment]
from the latest update 1.8.5, I still get the following error:

Traceback (most recent call last):
  File "C:\analysis\Noriben-master\Noriben-master\Noriben.py", line 1118, in parse_csv
    if int(float(reg_length)):
ValueError: could not convert string to float: '11\xa0566'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\analysis\Noriben-master\Noriben-master\Noriben.py", line 1570, in <module>
    main()
  File "C:\analysis\Noriben-master\Noriben-master\Noriben.py", line 1557, in main
    parse_csv(csv_file, report, timeline)
  File "C:\analysis\Noriben-master\Noriben-master\Noriben.py", line 1135, in parse_csv

I removed if int(float(reg_length)): from line 1118 and it seems to work better, no error messages this time.

**Comment by Rurik** [comment]
I'm sorry. I know this is super frustrating for everyone. Can you send me another set of logs? Unfortunately the last one expired before I could download, but I'm carving out time this weekend to fix this issue.

**Comment by lupinlicious** [comment]
@Rurik which logs do you need? .PML?

**Comment by Rurik** [comment]
PML is preferable, or the raw CSV that's created from that (the largest
file size one). So that I can see the raw data that was captured from
Procmon and is being fed in, and then can recreate it.

**Comment by lupinlicious** [comment]
@Rurik I have sent two files to your email brian@thebaskins.com
Did you get them?

Best regards

**Comment by Rurik** [comment]
Got them, thank you very much!
I'm carving out time this week to review.

**Comment by Rurik** [comment]
This issue is now resolved by new 1.8.6 release.
Thank you everyone for the help!
